# Generated by Django 5.1.1 on 2024-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('team_members', models.IntegerField(default=0)),
                ('earned', models.IntegerField(default=0)),
            ],
        ),
    ]
